### ISSUE TITLE
To many time installing pod

### ISSUE THREAD

**Issue by hugoerg56** [HipByte/motion-cocoapods#131]
Using motion-cocoapods 1.7.4 

 app.pods do |pod|
   ...pod 'AFNetworking', '~> 2.2'
    ...pod 'OpenKickflip', :git => 'https://github.com/hugoerg56/openkickflip-ios-sdk.git'
   ...pod 'FFmpeg', '2.2'
  end 

I'm Running rake pod:install and after 35mins.... :
https://monosnap.com/file/JN2D5FMFkHqdLzSWMDMKIKfcn2f9qx

any idea?

**Comment by Watson1978** [comment]
You can see progress when you use `COCOAPODS_VERBOSE` option.

```
$ rake pod:install COCOAPODS_VERBOSE=1
```

1) If no progress, I think you should remove local cocoapods repository in ~/.cocoapods, then set up it with `pod setup` using cocoapods command.

2) You should try CocoaPods command without motion-cocoapods. Run `pod install` with Xcode project.
If you meet same problem, there might be problem in CocoaPods.
You should report in https://github.com/CocoaPods/CocoaPods instead of here.

**Comment by Watson1978** [comment]
`CocoaPods` will install the libraries using `git`.
If library's git repository has the huge file, it will take a long time for `git clone` depending on the state of the network.

Unfortunately, we cannot solve this issue.
Please report to `CocoaPods`.
